Handle service enable on RHEL7 and above
The nfs service name has changed on RHEL7 (and derivatives) from **nfs** to **nfs-server**. 
Therefore the module does not handle correctly enabling the service.
```
Error: Could not enable nfs: 
Error: /Stage[main]/Nfs::Server::Redhat::Service/Service[nfs]/enable: change from false to true failed: Could not enable nfs: 
Notice: /Stage[main]/Nfs::Server::Redhat::Service/Service[nfs]: Triggered 'refresh' from 1 events
```

The following patch should fix this issue.